export const GET_TOKEN_SUCCESFUL = "GET_TOKEN_SUCCESFUL";
export const GET_TOKEN_PENDING = "GET_TOKEN_PENDING";
export const GET_TOKEN_FAILURE = "GET_TOKEN_FAILURE";
export const TOKEN_AUTH_FAILED = "TOKEN_AUTH_FAILED";

// Application Actions
export const APPLICATION_REQUEST_SUCCESS = "APPLICATION_REQUEST_SUCCESS";
export const APPLICATION_REQUEST_PENDING = "APPLICATION_REQUEST_PENDING";
export const DELETE_POPUP_CHANGE = "DELETE_POPUP_CHANGE";

//Edit Application Actions
export const EDIT_APPLICATION_REQUEST_SUCCESS =
  "EDIT_APPLICATION_REQUEST_SUCCESS";
export const EDIT_APPLICATION_REQUEST_PENDING =
  "EDIT_APPLICATION_REQUEST_PENDING";
export const EDIT_FORM_VIEW = "EDIT_FORM_VIEW";
export const OWNER_CHANGE = "OWNER_CHANGE";
export const TYPE_CHANGE = "TYPE_CHANGE";
export const CONTACT_CHANGE = "CONTACT_CHANGE";
export const APPROVED_STATUS_CHANGED = "APPROVED_STATUS_CHANGED";
export const DESCRIPTION_FIELD_CHANGED = "DESCRIPTION_FIELD_CHANGED";
export const DATE_FIELD_CHANGED = "DATE_FIELD_CHANGED";

//Theme Actions
export const GET_THEME_SUCCESFUL = "GET_THEME_SUCCESFUL";
export const GET_THEME_PENDING = "GET_THEME_PENDING";
export const GET_THEME_FAILURE = "GET_THEME_FAILURE";
export const TOGGLE_DARKTHEME = "TOGGLE_DARKTHEME";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";

// Customer Actions
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_PENDING = "GET_CONTACTS_PENDING";
export const CUSTOMER_MODAL_CHANGE = "CUSTOMER_MODAL_CHANGE";
export const DELETE_CONTACT_POPUP_CHANGE = "DELETE_CONTACT_POPUP_CHANGE";

//Vehicle Actions
export const GET_VEHICLES_SUCCESS = "GET_VEHICLES_SUCCESS";
export const GET_VEHICLES_PENDING = "GET_VEHICLES_PENDING";

//History Actions
export const GET_HISTORY_SUCCESS = "GET_HISTORY_SUCCESS";
export const GET_HISTORY_PENDING = "GET_HISTORY_PENDING";

// DashboardApplication Actions
export const GET_DASH_APPLICATIONS_SUCCESS = "GET_DASH_APPLICATIONS_SUCCESS";
export const GET_DASH_APPLICATIONS_PENDING = "GET_DASH_APPLICATIONS_PENDING";
export const GET_DASH_APPLICATIONS_FAILED = "GET_DASH_APPLICATIONS_FAILED";

// DashboardContacts Actions
export const GET_DASH_CONTACTS_SUCCESS = "GET_DASH_CONTACTS_SUCCESS";
export const GET_DASH_CONTACTS_PENDING = "GET_DASH_CONTACTS_PENDING";
export const GET_DASH_CONTACTS_FAILED = "GET_DASH_CONTACTS_FAILED";

// License Actions
export const LICENSE_REQUEST_SUCCESS = "LICENSE_REQUEST_SUCCESS";
export const LICENSE_REQUEST_PENDING = "LICENSE_REQUEST_PENDING";
export const DELETE_LICENSE_POPUP_CHANGE = "DELETE_LICENSE_POPUP_CHANGE";

//Edit Licenses Actions
export const EDIT_LICENSE_REQUEST_SUCCESS = "EDIT_LICENSE_REQUEST_SUCCESS";
export const EDIT_LICENSE_REQUEST_PENDING = "EDIT_LICENSE_REQUEST_PENDING";
export const EDIT_LICENSE_FORM_VIEW = "EDIT_LICENSE_FORM_VIEW";
export const LICENSE_OWNER_CHANGE = "LICENSE_OWNER_CHANGE";
export const LICENSE_TYPE_CHANGE = "LICENSE_TYPE_CHANGE";
export const LICENSE_STATUS_CHANGE = "LICENSE_STATUS_CHANGE";
