export const GET_TOKEN_SUCCESFUL = "GET_TOKEN_SUCCESFUL";
export const GET_TOKEN_PENDING = "GET_TOKEN_PENDING";
export const GET_TOKEN_FAILURE = "GET_TOKEN_FAILURE";
export const TOKEN_AUTH_FAILED = "TOKEN_AUTH_FAILED";

// Application Actions

export const APPLICATION_REQUEST_SUCCESS = "APPLICATION_REQUEST_SUCCESS";
export const APPLICATION_REQUEST_PENDING = "APPLICATION_REQUEST_PENDING";
export const DELETE_POPUP_CHANGE = "DELETE_POPUP_CHANGE";

//Edit Application Actions

export const EDIT_APPLICATION_REQUEST_SUCCESS = "EDIT_APPLICATION_REQUEST_SUCCESS";
export const EDIT_APPLICATION_REQUEST_PENDING = "EDIT_APPLICATION_REQUEST_PENDING";
export const EDIT_FORM_VIEW = "EDIT_FORM_VIEW";
export const OWNER_CHANGE = "OWNER_CHANGE";
export const TYPE_CHANGE = "TYPE_CHANGE";
export const CONTACT_CHANGE = 'CONTACT_CHANGE';
export const APPROVED_STATUS_CHANGED = 'APPROVED_STATUS_CHANGED';
export const DESCRIPTION_FIELD_CHANGED = 'DESCRIPTION_FIELD_CHANGED';
export const DATE_FIELD_CHANGED = "DATE_FIELD_CHANGED";
