export const GET_TOKEN_SUCCESFUL = "GET_TOKEN_SUCCESFUL";
export const GET_TOKEN_PENDING = "GET_TOKEN_PENDING";
export const GET_TOKEN_FAILURE = "GET_TOKEN_FAILURE";
export const TOKEN_AUTH_FAILED = "TOKEN_AUTH_FAILED";

// Application Actions
export const GET_APPLICATIONS = "GET_APPLICATIONS";
export const POST_APPLICATION = "POST_APPLICATION";

//Theme Actions
export const GET_THEME_SUCCESFUL = "GET_THEME_SUCCESFUL";
export const GET_THEME_PENDING = "GET_THEME_PENDING";
export const GET_THEME_FAILURE = "GET_THEME_FAILURE";
export const TOGGLE_DARKTHEME = "TOGGLE_DARKTHEME";
